### PR TITLE
tcpWER

### PR DESCRIPTION
**Pull request by boeddeker**
I started with the scoring script and tried to get your ideas for it from the README, the template code and the da_wer_scoring script.

Is that going in the right direction?

ToDo:
 - [x] uem
 - [x] cpWER
 - [x] normalize

### CODE REVIEW

**Comment by popcornell** [comment]
Oh thank you very much ! 

Yes it looks in the right direction. 
We need also to apply the normalization to the predictions. 
You can use https://github.com/chimechallenge/chime-utils/blob/2b39657966ece6fbafa4dba093092232cc41fca7/chime_utils/text_norm/__init__.py#L5 I guess

**Comment by boeddeker** [comment]
Great. I knew that I forgot something in the todo list.

**Comment by popcornell** [comment]
Should I review ?

**Comment by boeddeker** [comment]
yes

**Comment by popcornell** [comment]
I think it looks good. 
I tested it with ESPNet recipe

**Pull request merged**
